/*CREATE FUNCTION metin_metinparcala(@METIN VARCHAR(100),@AYRAC CHAR(1))
RETURNS @SONUC TABLE (ISIM VARCHAR(20))

BEGIN 
DECLARE @BAS INT,@BIT INT
SET @BAS =1
SET @BIT= (SELECT CHARINDEX(@AYRAC,@METIN))

WHILE @BAS< LEN(@METIN) +1
BEGIN

IF @BIT=0
 SET @BIT=LEN(@METIN)+1

INSERT INTO @SONUC(ISIM) VALUES (SUBSTRING(@METIN,@BAS,@BIT-@BAS))

SET @BAS=@BIT+1
SET @BIT=CHARINDEX(@AYRAC,@METIN,@BAS)
END
RETURN

END
*/
--BAS=KIRAZ, BIT-BAS=ELMA,BIT=ARMUT 
SELECT * FROM dbo.metin_metinparcala('MATEMATIK,VERÝTABANI,LINEERCEBIR',',') --CALISTIRILIR