 --USE TEST 
select * from KITAPLAR 

SELECT * FROM YAYINEVLERI


SELECT * FROM KITAPLAR, YAYINEVLERI -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
WHERE KITAPLAR.YV_NO=YAYINEVLERI.NO


SELECT * FROM KITAPLAR INNER JOIN YAYINEVLERI -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
ON KITAPLAR.YV_NO=YAYINEVLERI.NO


SELECT * FROM KITAPLAR JOIN YAYINEVLERI -- INNER JOIN SADECE JOIN YAZARAK DA YAPILABILIR
ON KITAPLAR.YV_NO=YAYINEVLERI.NO


SELECT * FROM KITAPLAR AS kitaptablosu, YAYINEVLERI AS yayinevi -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
WHERE kitaptablosu.YV_NO=yayinevi.NO -- TABLOLARA ALÝAS ÝLE YENÝ ÝSÝM VEREREK 


SELECT K.NO, K.ISIM, Y.NO, Y.ISIM FROM KITAPLAR AS K, YAYINEVLERI AS Y -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
WHERE K.YV_NO=Y.NO -- TABLOLARA ALÝAS ÝLE YENÝ ÝSÝM VEREREK 


SELECT KITAPLAR.ISIM FROM KITAPLAR, YAYINEVLERI -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
WHERE KITAPLAR.YV_NO=YAYINEVLERI.NO -- TABLOLARA ALÝAS ÝLE YENÝ ÝSÝM VEREREK 
UNION  -- ÝKÝ SORGUYU BÝRLEÞTÝRÝR (uNION all TEKRAR EDEN KAYITLARI TEKRAR ALIR. UNION yazarsak tek bir defa alýr)
SELECT YAYINEVLERI.ISIM FROM KITAPLAR INNER JOIN YAYINEVLERI  -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
ON KITAPLAR.YV_NO=YAYINEVLERI.NO -- TABLOLARA ALÝAS ÝLE YENÝ ÝSÝM VEREREK 

SELECT KITAPLAR.ISIM FROM KITAPLAR, YAYINEVLERI -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
WHERE KITAPLAR.YV_NO=YAYINEVLERI.NO -- TABLOLARA ALÝAS ÝLE YENÝ ÝSÝM VEREREK 
UNION ALL -- ÝKÝ SORGUYU BÝRLEÞTÝRÝR (uNION all TEKRAR EDEN KAYITLARI TEKRAR ALIR. UNION yazarsak tek bir defa alýr)
SELECT YAYINEVLERI.ISIM FROM KITAPLAR INNER JOIN YAYINEVLERI  -- ÝLÝÞKÝLÝ ÝKÝ FARKLI TABLODAN VERÝ ÇEKME
ON KITAPLAR.YV_NO=YAYINEVLERI.NO -- TABLOLARA ALÝAS ÝLE YENÝ ÝSÝM VEREREK 



--3 TABLO OLURSA

SELECT * FROM kitaplar K
SELECT * FROM YAZARLAR 
SELECT * FROM KITAPYAZAR


SELECT * FROM KITAPLAR K , YAZARLAR Y, KITAPYAZAR KY WHERE K.NO=KY.KNO AND Y.YAZAR_NO=KY.YNO

SELECT * FROM KITAPLAR K INNER JOIN KITAPYAZAR KY ON K.ISIM LIKE '%B%' AND K.NO=KY.KNO INNER JOIN YAZARLAR  Y on  Y.DOGUM_YILI >1800 AND Y.YAZAR_NO= KY.YNO 
