--výew kullaným 

--soru1  --iþlem gerçekleþtirildi 2inci defa çalýþtýrýldýðýnda hata verir çünkü onceden çalýþtýrdýk
 --CREATE VIEW V_AD_SOYAD  AS  
--select p.ISIM,p.SOYISIM from PERSONEL p  --alter create ile günceleme olur
select * from V_AD_SOYAD
CREATE VIEW V_AD_SOYAD_GIZLI WITH ENCRYPTION  AS
select p.ISIM,p.SOYISIM from PERSONEL p
SELECT * FROM V_AD_SOYAD_GIZLI

--SORU2
ALTER VIEW V_MAAS_RAPOR AS
SELECT  COUNT(*) AS KÝSÝ_SAYÝSÝ,MIN(P.MAAS) AS MINMAAS,MAX(P.MAAS) AS MAXMAAS,
AVG(P.MAAS) AS ORTALAMA, SUM(P.MAAS) AS TOPLAMMAAS FROM PERSONEL P
 SELECT * FROM V_MAAS_RAPOR

 --SORU3 

 CREATE VIEW V_KITAP_YAZAR AS
 SELECT Y.ISIM,Y.SOYISIM,K.ISIM  AS KÝTAP_ADI FROM KITAPLAR K, YAZARLAR Y, KITAPYAZAR KY WHERE K.NO= KY.KNO
 AND Y.YAZAR_NO= KY.YNO
 SELECT * FROM V_KITAP_YAZAR V WHERE V.KÝTAP_ADI LIKE('%Q%')

 --SORU4
 CREATE VIEW V_G_MAAS AS 
 SELECT AVG(P.MAAS) AS ORT_MAAS FROM PERSONEL P
  SELECT  TOP 1* FROM PERSONEL P,V_G_MAAS V WHERE P.MAAS> V.ORT_MAAS ORDER BY P.MAAS
  -- TOP1 ÝLK VERÝYÝ VERÝR SADECE

  --SORU5
  ALTER VIEW V_G_MAAS AS
  SELECT P.ULKE,AVG(P.MAAS) AS ORT_MAAS FROM PERSONEL P GROUP BY P.ULKE
   SELECT  * FROM PERSONEL P,V_G_MAAS V WHERE P.ULKE=V.ULKE 


   CREATE VIEW VIEW1 AS 
 SELECT *FROM PERSONEL 
   SELECT * FROM VIEW1

   UPDATE VIEW1 SET MAAS=5000 WHERE ULKE='TÜRKÝYE'
      UPDATE VIEW1 SET MAAS=1000 WHERE ULKE='ABD'




